name: Deploy to Reaction Internet

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # If your site needs a build step (Vite, Next static export, etc.),
      # uncomment and adjust these lines, and also change local_path below to the build folder.
      # - name: Install deps
      #   run: npm ci
      # - name: Build
      #   run: npm run build

      - name: Upload via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT || 22 }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          local_path: ./                # change to ./dist or ./build if you build
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}
          sftp_only: true
          delete_remote_files: false    # set true if you want exact sync
          exclude: |
            .git*
            .github/
            node_modules/
            README.md
